/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum TargetType {
  Class = 0,
  TSInterface = 1,
  TSTypeAlias = 2,
  Variable = 3
}
export interface OutputCode {
  code: string
  targetType: TargetType
  path: string
}
export declare function resolve(path: string, libFilePath: string, tsConfigPath?: string | undefined | null): Record<string, OutputCode> | null
export declare function generatetest(output: Record<string, OutputCode>): void
