/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OutputCode {
  code: string
  path: string
}
export declare function resolve(path: string, tsConfigPath?: string | undefined | null): Record<string, OutputCode> | null
export declare function generatetest(output: Record<string, OutputCode>): void
