✅✅✅ hoge <ref *3> NodeObject {
  pos: 392,
  end: 407,
  kind: 184,
  id: 8,
  flags: 0,
  modifierFlagsCache: 0,
  transformFlags: 1,
  parent: <ref *4> NodeObject {
    pos: 376,
    end: 408,
    kind: 171,
    id: 0,
    flags: 0,
    modifierFlagsCache: 536870912,
    transformFlags: 1,
    parent: <ref *1> NodeObject {
      pos: 257,
      end: 423,
      kind: 264,
      id: 0,
      flags: 0,
      modifierFlagsCache: 536870912,
      transformFlags: 1,
      parent: <ref *2> SourceFileObject {
        pos: 0,
        end: 423,
        kind: 307,
        id: 0,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: undefined,
        original: undefined,
        emitNode: undefined,
        statements: [
          [NodeObject],
          [NodeObject],
          [Circular *1],
          pos: 0,
          end: 423,
          hasTrailingComma: false,
          transformFlags: 1
        ],
        endOfFileToken: TokenObject {
          pos: 423,
          end: 423,
          kind: 1,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *2],
          emitNode: undefined
        },
        text: "type main = ref_8fa900714581ef4b0ef680d700516c6a590097bd4bc2adbb44922c3a99774834;\n" +
          "type ref_8fa900714"... 323 more characters,
        fileName: "example.ts",
        path: "/users/tanaka-masato/private/boostest/example.ts",
        resolvedPath: "/users/tanaka-masato/private/boostest/example.ts",
        originalFileName: "example.ts",
        languageVersion: 99,
        languageVariant: 0,
        scriptKind: 3,
        isDeclarationFile: false,
        hasNoDefaultLib: false,
        locals: Map(3) {
          "main" => [SymbolObject],
          "ref_8fa900714581ef4b0ef680d700516c6a590097bd4bc2adbb44922c3a99774834" => [SymbolObject],
          "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a" => [SymbolObject]
        },
        nextContainer: NodeObject {
          pos: 0,
          end: 81,
          kind: 265,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *2],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          name: [IdentifierObject],
          typeParameters: undefined,
          type: [NodeObject],
          jsDoc: undefined,
          locals: Map(0) {},
          nextContainer: [NodeObject]
        },
        endFlowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        nodeCount: 46,
        identifierCount: 20,
        symbolCount: 14,
        parseDiagnostics: [],
        bindDiagnostics: [],
        bindSuggestionDiagnostics: undefined,
        lineMap: undefined,
        externalModuleIndicator: undefined,
        setExternalModuleIndicator: [Function: setExternalModuleIndicator],
        pragmas: Map(0) {},
        checkJsDirective: undefined,
        referencedFiles: [],
        typeReferenceDirectives: [],
        libReferenceDirectives: [],
        amdDependencies: [],
        commentDirectives: undefined,
        identifiers: Map(11) {
          "main" => "main",
          "ref_8fa900714581ef4b0ef680d700516c6a590097bd4bc2adbb44922c3a99774834" => "ref_8fa900714581ef4b0ef680d700516c6a590097bd4bc2adbb44922c3a99774834",
          "map" => "map",
          "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a" => "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a",
          "K" => "K",
          "V" => "V",
          "get" => "get",
          "key" => "key",
          "sampleFunc" => "sampleFunc",
          "name" => "name",
          "hoge" => "hoge"
        },
        packageJsonLocations: undefined,
        packageJsonScope: undefined,
        imports: [],
        moduleAugmentations: [],
        ambientModuleNames: [],
        classifiableNames: Set(5) {
          "main",
          "ref_8fa900714581ef4b0ef680d700516c6a590097bd4bc2adbb44922c3a99774834",
          "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a",
          "K",
          "V"
        },
        impliedNodeFormat: undefined,
        jsDocParsingMode: 0
      },
      original: undefined,
      emitNode: undefined,
      symbol: SymbolObject {
        flags: 64,
        escapedName: "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a",
        declarations: [ [Circular *1] ],
        valueDeclaration: undefined,
        id: 4,
        mergeId: 0,
        parent: undefined,
        members: Map(5) {
          "K" => [SymbolObject],
          "V" => [SymbolObject],
          "get" => [SymbolObject],
          "sampleFunc" => [SymbolObject],
          "hoge" => [SymbolObject]
        },
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      localSymbol: undefined,
      modifiers: undefined,
      name: IdentifierObject {
        pos: 267,
        end: 336,
        kind: 80,
        id: 0,
        flags: 0,
        transformFlags: 0,
        parent: [Circular *1],
        emitNode: undefined,
        escapedText: "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a",
        jsDoc: undefined,
        flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        symbol: undefined
      },
      typeParameters: [
        NodeObject {
          pos: 337,
          end: 338,
          kind: 168,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *1],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          name: [IdentifierObject],
          constraint: undefined,
          default: undefined,
          expression: undefined,
          jsDoc: undefined
        },
        NodeObject {
          pos: 339,
          end: 341,
          kind: 168,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *1],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          name: [IdentifierObject],
          constraint: undefined,
          default: undefined,
          expression: undefined,
          jsDoc: undefined
        },
        pos: 337,
        end: 341,
        hasTrailingComma: false,
        transformFlags: 1
      ],
      heritageClauses: undefined,
      members: [
        NodeObject {
          pos: 344,
          end: 376,
          kind: 173,
          id: 4,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *1],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          name: [IdentifierObject],
          questionToken: undefined,
          typeParameters: undefined,
          parameters: [Array],
          type: [NodeObject],
          jsDoc: undefined,
          locals: [Map],
          nextContainer: [Circular *3],
          typeArguments: undefined
        },
        [Circular *4],
        NodeObject {
          pos: 408,
          end: 421,
          kind: 171,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *1],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          name: [IdentifierObject],
          type: [NodeObject],
          questionToken: undefined,
          initializer: undefined,
          jsDoc: undefined
        },
        pos: 344,
        end: 421,
        hasTrailingComma: false,
        transformFlags: 1
      ],
      jsDoc: undefined
    },
    original: undefined,
    emitNode: undefined,
    symbol: <ref *5> SymbolObject {
      flags: 4,
      escapedName: "sampleFunc",
      declarations: [ [Circular *4] ],
      valueDeclaration: [Circular *4],
      id: 8,
      mergeId: 0,
      parent: SymbolObject {
        flags: 64,
        escapedName: "ref_f5ef5f60613beeb2ba63d47b09fc9021370fb07cba141862733631b79f14bd7a",
        declarations: [ [NodeObject] ],
        valueDeclaration: undefined,
        id: 4,
        mergeId: 0,
        parent: undefined,
        members: Map(5) {
          "K" => [SymbolObject],
          "V" => [SymbolObject],
          "get" => [SymbolObject],
          "sampleFunc" => [Circular *5],
          "hoge" => [SymbolObject]
        },
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      members: undefined,
      exports: undefined,
      exportSymbol: undefined,
      constEnumOnlyModule: undefined,
      isReferenced: undefined,
      lastAssignmentPos: undefined,
      links: undefined
    },
    localSymbol: undefined,
    modifiers: undefined,
    name: IdentifierObject {
      pos: 376,
      end: 391,
      kind: 80,
      id: 0,
      flags: 0,
      transformFlags: 0,
      parent: [Circular *4],
      emitNode: undefined,
      escapedText: "sampleFunc",
      jsDoc: undefined,
      flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
      symbol: undefined
    },
    type: [Circular *3],
    questionToken: undefined,
    initializer: undefined,
    jsDoc: undefined
  },
  original: undefined,
  emitNode: undefined,
  symbol: SymbolObject {
    flags: 2048,
    escapedName: "__type",
    declarations: [ [Circular *3] ],
    valueDeclaration: undefined,
    id: 11,
    mergeId: 0,
    parent: undefined,
    members: Map(1) {
      "__call" => SymbolObject {
        flags: 131072,
        escapedName: "__call",
        declarations: [ [Circular *3] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: undefined,
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      }
    },
    exports: undefined,
    exportSymbol: undefined,
    constEnumOnlyModule: undefined,
    isReferenced: undefined,
    lastAssignmentPos: undefined,
    links: undefined
  },
  localSymbol: undefined,
  typeParameters: undefined,
  parameters: [
    <ref *6> NodeObject {
      pos: 394,
      end: 401,
      kind: 169,
      id: 0,
      flags: 0,
      modifierFlagsCache: 536870912,
      transformFlags: 1,
      parent: [Circular *3],
      original: undefined,
      emitNode: undefined,
      symbol: SymbolObject {
        flags: 1,
        escapedName: "name",
        declarations: [ [Circular *6] ],
        valueDeclaration: [Circular *6],
        id: 12,
        mergeId: 0,
        parent: undefined,
        members: undefined,
        exports: Map(0) {},
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      localSymbol: undefined,
      modifiers: undefined,
      dotDotDotToken: undefined,
      name: IdentifierObject {
        pos: 394,
        end: 398,
        kind: 80,
        id: 0,
        flags: 0,
        transformFlags: 0,
        parent: [Circular *6],
        emitNode: undefined,
        escapedText: "name",
        jsDoc: undefined,
        flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        symbol: undefined
      },
      questionToken: undefined,
      type: <ref *7> NodeObject {
        pos: 399,
        end: 401,
        kind: 183,
        id: 9,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: [Circular *6],
        original: undefined,
        emitNode: undefined,
        typeName: IdentifierObject {
          pos: 399,
          end: 401,
          kind: 80,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *7],
          emitNode: undefined,
          escapedText: "K",
          jsDoc: undefined,
          flowNode: [Object],
          symbol: undefined
        },
        typeArguments: undefined
      },
      initializer: undefined,
      jsDoc: undefined
    },
    pos: 394,
    end: 401,
    hasTrailingComma: false,
    transformFlags: 1
  ],
  type: <ref *8> NodeObject {
    pos: 405,
    end: 407,
    kind: 183,
    id: 10,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 1,
    parent: [Circular *3],
    original: undefined,
    emitNode: undefined,
    typeName: IdentifierObject {
      pos: 405,
      end: 407,
      kind: 80,
      id: 0,
      flags: 0,
      transformFlags: 0,
      parent: [Circular *8],
      emitNode: undefined,
      escapedText: "V",
      jsDoc: undefined,
      flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
      symbol: undefined
    },
    typeArguments: undefined
  },
  modifiers: undefined,
  jsDoc: undefined,
  locals: Map(1) {
    "name" => <ref *9> SymbolObject {
      flags: 1,
      escapedName: "name",
      declarations: [
        <ref *6> NodeObject {
          pos: 394,
          end: 401,
          kind: 169,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870912,
          transformFlags: 1,
          parent: [Circular *3],
          original: undefined,
          emitNode: undefined,
          symbol: [Circular *9],
          localSymbol: undefined,
          modifiers: undefined,
          dotDotDotToken: undefined,
          name: [IdentifierObject],
          questionToken: undefined,
          type: [NodeObject],
          initializer: undefined,
          jsDoc: undefined
        }
      ],
      valueDeclaration: <ref *6> NodeObject {
        pos: 394,
        end: 401,
        kind: 169,
        id: 0,
        flags: 0,
        modifierFlagsCache: 536870912,
        transformFlags: 1,
        parent: [Circular *3],
        original: undefined,
        emitNode: undefined,
        symbol: [Circular *9],
        localSymbol: undefined,
        modifiers: undefined,
        dotDotDotToken: undefined,
        name: IdentifierObject {
          pos: 394,
          end: 398,
          kind: 80,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *6],
          emitNode: undefined,
          escapedText: "name",
          jsDoc: undefined,
          flowNode: [Object],
          symbol: undefined
        },
        questionToken: undefined,
        type: <ref *7> NodeObject {
          pos: 399,
          end: 401,
          kind: 183,
          id: 9,
          flags: 0,
          modifierFlagsCache: 0,
          transformFlags: 1,
          parent: [Circular *6],
          original: undefined,
          emitNode: undefined,
          typeName: [IdentifierObject],
          typeArguments: undefined
        },
        initializer: undefined,
        jsDoc: undefined
      },
      id: 12,
      mergeId: 0,
      parent: undefined,
      members: undefined,
      exports: Map(0) {},
      exportSymbol: undefined,
      constEnumOnlyModule: undefined,
      isReferenced: undefined,
      lastAssignmentPos: undefined,
      links: undefined
    }
  },
  nextContainer: undefined,
  typeArguments: undefined
}

