NodeObject {
  pos: 13,
  end: 35,
  kind: 171,
  id: 0,
  flags: 0,
  modifierFlagsCache: 536870912,
  transformFlags: 1,
  parent: <ref *3> NodeObject {
    pos: 11,
    end: 37,
    kind: 187,
    id: 1,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 1,
    parent: <ref *1> NodeObject {
      pos: 0,
      end: 38,
      kind: 265,
      id: 0,
      flags: 0,
      modifierFlagsCache: 536870912,
      transformFlags: 1,
      parent: <ref *2> SourceFileObject {
        pos: 0,
        end: 38,
        kind: 307,
        id: 0,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: undefined,
        original: undefined,
        emitNode: undefined,
        statements: [
          [Circular *1],
          pos: 0,
          end: 38,
          hasTrailingComma: false,
          transformFlags: 1
        ],
        endOfFileToken: TokenObject {
          pos: 38,
          end: 38,
          kind: 1,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *2],
          emitNode: undefined
        },
        text: "type main = {\n    func: () => void;\n};",
        fileName: "example.ts",
        path: "/users/tanaka-masato/private/boostest/example.ts",
        resolvedPath: "/users/tanaka-masato/private/boostest/example.ts",
        originalFileName: "example.ts",
        languageVersion: 99,
        languageVariant: 0,
        scriptKind: 3,
        isDeclarationFile: false,
        hasNoDefaultLib: false,
        locals: Map(1) { "main" => [SymbolObject] },
        nextContainer: [Circular *1],
        endFlowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        nodeCount: 9,
        identifierCount: 2,
        symbolCount: 5,
        parseDiagnostics: [],
        bindDiagnostics: [],
        bindSuggestionDiagnostics: undefined,
        lineMap: undefined,
        externalModuleIndicator: undefined,
        setExternalModuleIndicator: [Function: setExternalModuleIndicator],
        pragmas: Map(0) {},
        checkJsDirective: undefined,
        referencedFiles: [],
        typeReferenceDirectives: [],
        libReferenceDirectives: [],
        amdDependencies: [],
        commentDirectives: undefined,
        identifiers: Map(2) { "main" => "main", "func" => "func" },
        packageJsonLocations: undefined,
        packageJsonScope: undefined,
        imports: [],
        moduleAugmentations: [],
        ambientModuleNames: [],
        classifiableNames: Set(1) { "main" },
        impliedNodeFormat: undefined,
        jsDocParsingMode: 0
      },
      original: undefined,
      emitNode: undefined,
      symbol: SymbolObject {
        flags: 524288,
        escapedName: "main",
        declarations: [ [Circular *1] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: undefined,
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      localSymbol: undefined,
      modifiers: undefined,
      name: IdentifierObject {
        pos: 4,
        end: 9,
        kind: 80,
        id: 0,
        flags: 0,
        transformFlags: 0,
        parent: [Circular *1],
        emitNode: undefined,
        escapedText: "main",
        jsDoc: undefined,
        flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        symbol: undefined
      },
      typeParameters: undefined,
      type: [Circular *3],
      jsDoc: undefined,
      locals: Map(0) {},
      nextContainer: <ref *5> NodeObject {
        pos: 23,
        end: 34,
        kind: 184,
        id: 0,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: [Circular *4],
        original: undefined,
        emitNode: undefined,
        symbol: SymbolObject {
          flags: 2048,
          escapedName: "__type",
          declarations: [Array],
          valueDeclaration: undefined,
          id: 0,
          mergeId: 0,
          parent: undefined,
          members: [Map],
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        },
        localSymbol: undefined,
        typeParameters: undefined,
        parameters: [
          pos: 25,
          end: 25,
          hasTrailingComma: false,
          transformFlags: 0
        ],
        type: TokenObject {
          pos: 29,
          end: 34,
          kind: 116,
          id: 0,
          flags: 0,
          transformFlags: 1,
          parent: [Circular *5],
          emitNode: undefined
        },
        modifiers: undefined,
        jsDoc: undefined,
        locals: Map(0) {},
        nextContainer: undefined,
        typeArguments: undefined
      }
    },
    original: undefined,
    emitNode: undefined,
    symbol: <ref *6> SymbolObject {
      flags: 2048,
      escapedName: "__type",
      declarations: [ [Circular *3] ],
      valueDeclaration: undefined,
      id: 1,
      mergeId: 0,
      parent: undefined,
      members: Map(1) {
        "func" => SymbolObject {
          flags: 4,
          escapedName: "func",
          declarations: [Array],
          valueDeclaration: [Circular *4],
          id: 0,
          mergeId: 0,
          parent: [Circular *6],
          members: undefined,
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        }
      },
      exports: undefined,
      exportSymbol: undefined,
      constEnumOnlyModule: undefined,
      isReferenced: undefined,
      lastAssignmentPos: undefined,
      links: undefined
    },
    localSymbol: undefined,
    members: [
      [Circular *4],
      pos: 13,
      end: 35,
      hasTrailingComma: false,
      transformFlags: 1
    ]
  },
  original: undefined,
  emitNode: undefined,
  symbol: <ref *7> SymbolObject {
    flags: 4,
    escapedName: "func",
    declarations: [ [Circular *4] ],
    valueDeclaration: [Circular *4],
    id: 0,
    mergeId: 0,
    parent: <ref *6> SymbolObject {
      flags: 2048,
      escapedName: "__type",
      declarations: [
        <ref *3> NodeObject {
          pos: 11,
          end: 37,
          kind: 187,
          id: 1,
          flags: 0,
          modifierFlagsCache: 0,
          transformFlags: 1,
          parent: [NodeObject],
          original: undefined,
          emitNode: undefined,
          symbol: [Circular *6],
          localSymbol: undefined,
          members: [Array]
        }
      ],
      valueDeclaration: undefined,
      id: 1,
      mergeId: 0,
      parent: undefined,
      members: Map(1) { "func" => [Circular *7] },
      exports: undefined,
      exportSymbol: undefined,
      constEnumOnlyModule: undefined,
      isReferenced: undefined,
      lastAssignmentPos: undefined,
      links: undefined
    },
    members: undefined,
    exports: undefined,
    exportSymbol: undefined,
    constEnumOnlyModule: undefined,
    isReferenced: undefined,
    lastAssignmentPos: undefined,
    links: undefined
  },
  localSymbol: undefined,
  modifiers: undefined,
  name: IdentifierObject {
    pos: 13,
    end: 22,
    kind: 80,
    id: 0,
    flags: 0,
    transformFlags: 0,
    parent: [Circular *4],
    emitNode: undefined,
    escapedText: "func",
    jsDoc: undefined,
    flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
    symbol: undefined
  },
  type: <ref *5> NodeObject {
    pos: 23,
    end: 34,
    kind: 184,
    id: 0,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 1,
    parent: [Circular *4],
    original: undefined,
    emitNode: undefined,
    symbol: SymbolObject {
      flags: 2048,
      escapedName: "__type",
      declarations: [ [Circular *5] ],
      valueDeclaration: undefined,
      id: 0,
      mergeId: 0,
      parent: undefined,
      members: Map(1) {
        "__call" => SymbolObject {
          flags: 131072,
          escapedName: "__call",
          declarations: [Array],
          valueDeclaration: undefined,
          id: 0,
          mergeId: 0,
          parent: undefined,
          members: undefined,
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        }
      },
      exports: undefined,
      exportSymbol: undefined,
      constEnumOnlyModule: undefined,
      isReferenced: undefined,
      lastAssignmentPos: undefined,
      links: undefined
    },
    localSymbol: undefined,
    typeParameters: undefined,
    parameters: [ pos: 25, end: 25, hasTrailingComma: false, transformFlags: 0 ],
    type: TokenObject {
      pos: 29,
      end: 34,
      kind: 116,
      id: 0,
      flags: 0,
      transformFlags: 1,
      parent: [Circular *5],
      emitNode: undefined
    },
    modifiers: undefined,
    jsDoc: undefined,
    locals: Map(0) {},
    nextContainer: undefined,
    typeArguments: undefined
  },
  questionToken: undefined,
  initializer: undefined,
  jsDoc: undefined
}
