  pos: 81,
  end: 205,
  kind: 263,
  id: 0,
  flags: 0,
  modifierFlagsCache: 536870912,
  transformFlags: 9217,
  parent: <ref *1> SourceFileObject {
    pos: 0,
    end: 205,
    kind: 307,
    id: 0,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 1025,
    parent: undefined,
    original: undefined,
    emitNode: undefined,
    statements: [
      <ref *2> NodeObject {
        pos: 0,
        end: 81,
        kind: 265,
        id: 0,
        flags: 0,
        modifierFlagsCache: 536870912,
        transformFlags: 1,
        parent: [Circular *1],
        original: undefined,
        emitNode: undefined,
        symbol: SymbolObject {
          flags: 524288,
          escapedName: "main",
          declarations: [Array],
          valueDeclaration: undefined,
          id: 0,
          mergeId: 0,
          parent: undefined,
          members: undefined,
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        },
        localSymbol: undefined,
        modifiers: undefined,
        name: IdentifierObject {
          pos: 4,
          end: 9,
          kind: 80,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *2],
          emitNode: undefined,
          escapedText: "main",
          jsDoc: undefined,
          flowNode: [Object],
          symbol: undefined
        },
        typeParameters: undefined,
        type: NodeObject {
          pos: 11,
          end: 80,
          kind: 183,
          id: 1,
          flags: 0,
          modifierFlagsCache: 0,
          transformFlags: 1,
          parent: [Circular *2],
          original: undefined,
          emitNode: undefined,
          typeName: [IdentifierObject],
          typeArguments: undefined
        },
        jsDoc: undefined,
        locals: Map(0) {},
        nextContainer: NodeObject {
          pos: 158,
          end: 203,
          kind: 176,
          id: 0,
          flags: 512,
          modifierFlagsCache: 536870912,
          transformFlags: 9217,
          parent: [Circular *3],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: undefined,
          parameters: [Array],
          body: [NodeObject],
          typeParameters: undefined,
          type: undefined,
          typeArguments: undefined,
          jsDoc: undefined,
          locals: [Map],
          nextContainer: [NodeObject],
          endFlowNode: [Object],
          returnFlowNode: [Object]
        }
      },
      [Circular *3],
      pos: 0,
      end: 205,
      hasTrailingComma: false,
      transformFlags: 1025
    ],
    endOfFileToken: TokenObject {
      pos: 205,
      end: 205,
      kind: 1,
      id: 0,
      flags: 0,
      transformFlags: 0,
      parent: [Circular *1],
      emitNode: undefined
    },
    text: "type main = ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6;\n" +
      "class ref_da030cb1"... 105 more characters,
    fileName: "example.ts",
    path: "/Users/tanaka-masato/private/boostest/example.ts",
    resolvedPath: "/Users/tanaka-masato/private/boostest/example.ts",
    originalFileName: "example.ts",
    languageVersion: 99,
    languageVariant: 0,
    scriptKind: 3,
    isDeclarationFile: false,
    hasNoDefaultLib: false,
    locals: Map(2) {
      "main" => SymbolObject {
        flags: 524288,
        escapedName: "main",
        declarations: [ [NodeObject] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: undefined,
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6" => SymbolObject {
        flags: 32,
        escapedName: "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
        declarations: [ [Circular *3] ],
        valueDeclaration: [Circular *3],
        id: 1,
        mergeId: 0,
        parent: undefined,
        members: Map(2) {
          "__constructor" => [SymbolObject],
          "hoge" => [SymbolObject]
        },
        exports: Map(1) { "prototype" => [SymbolObject] },
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      }
    },
    nextContainer: <ref *2> NodeObject {
      pos: 0,
      end: 81,
      kind: 265,
      id: 0,
      flags: 0,
      modifierFlagsCache: 536870912,
      transformFlags: 1,
      parent: [Circular *1],
      original: undefined,
      emitNode: undefined,
      symbol: SymbolObject {
        flags: 524288,
        escapedName: "main",
        declarations: [ [Circular *2] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: undefined,
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      localSymbol: undefined,
      modifiers: undefined,
      name: IdentifierObject {
        pos: 4,
        end: 9,
        kind: 80,
        id: 0,
        flags: 0,
        transformFlags: 0,
        parent: [Circular *2],
        emitNode: undefined,
        escapedText: "main",
        jsDoc: undefined,
        flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
        symbol: undefined
      },
      typeParameters: undefined,
      type: <ref *4> NodeObject {
        pos: 11,
        end: 80,
        kind: 183,
        id: 1,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: [Circular *2],
        original: undefined,
        emitNode: undefined,
        typeName: IdentifierObject {
          pos: 11,
          end: 80,
          kind: 80,
          id: 0,
          flags: 0,
          transformFlags: 0,
          parent: [Circular *4],
          emitNode: undefined,
          escapedText: "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
          jsDoc: undefined,
          flowNode: [Object],
          symbol: undefined
        },
        typeArguments: undefined
      },
      jsDoc: undefined,
      locals: Map(0) {},
      nextContainer: <ref *5> NodeObject {
        pos: 158,
        end: 203,
        kind: 176,
        id: 0,
        flags: 512,
        modifierFlagsCache: 536870912,
        transformFlags: 9217,
        parent: [Circular *3],
        original: undefined,
        emitNode: undefined,
        symbol: SymbolObject {
          flags: 16384,
          escapedName: "__constructor",
          declarations: [Array],
          valueDeclaration: undefined,
          id: 0,
          mergeId: 0,
          parent: [SymbolObject],
          members: undefined,
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        },
        localSymbol: undefined,
        modifiers: undefined,
        parameters: [
          [NodeObject],
          pos: 175,
          end: 198,
          hasTrailingComma: false,
          transformFlags: 8193
        ],
        body: NodeObject {
          pos: 199,
          end: 203,
          kind: 241,
          id: 0,
          flags: 0,
          modifierFlagsCache: 0,
          transformFlags: 0,
          parent: [Circular *5],
          original: undefined,
          emitNode: undefined,
          statements: [Array],
          multiLine: false,
          jsDoc: undefined,
          locals: undefined,
          nextContainer: undefined
        },
        typeParameters: undefined,
        type: undefined,
        typeArguments: undefined,
        jsDoc: undefined,
        locals: Map(1) { "hoge" => [SymbolObject] },
        nextContainer: NodeObject {
          pos: 187,
          end: 198,
          kind: 184,
          id: 0,
          flags: 0,
          modifierFlagsCache: 0,
          transformFlags: 1,
          parent: [NodeObject],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          typeParameters: undefined,
          parameters: [Array],
          type: [TokenObject],
          modifiers: undefined,
          jsDoc: undefined,
          locals: Map(0) {},
          nextContainer: undefined,
          typeArguments: undefined
        },
        endFlowNode: { flags: 2050, id: 0, node: undefined, antecedent: undefined },
        returnFlowNode: { flags: 2050, id: 0, node: undefined, antecedent: undefined }
      }
    },
    endFlowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
    nodeCount: 15,
    identifierCount: 4,
    symbolCount: 8,
    parseDiagnostics: [],
    bindDiagnostics: [],
    bindSuggestionDiagnostics: undefined,
    lineMap: undefined,
    externalModuleIndicator: undefined,
    setExternalModuleIndicator: [Function: setExternalModuleIndicator],
    pragmas: Map(0) {},
    checkJsDirective: undefined,
    referencedFiles: [],
    typeReferenceDirectives: [],
    libReferenceDirectives: [],
    amdDependencies: [],
    commentDirectives: undefined,
    identifiers: Map(3) {
      "main" => "main",
      "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6" => "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
      "hoge" => "hoge"
    },
    packageJsonLocations: undefined,
    packageJsonScope: undefined,
    imports: [],
    moduleAugmentations: [],
    ambientModuleNames: [],
    classifiableNames: Set(2) {
      "main",
      "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6"
    },
    impliedNodeFormat: undefined,
    jsDocParsingMode: 0
  },
  original: undefined,
  emitNode: undefined,
  symbol: <ref *6> SymbolObject {
    flags: 32,
    escapedName: "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
    declarations: [ [Circular *3] ],
    valueDeclaration: [Circular *3],
    id: 1,
    mergeId: 0,
    parent: undefined,
    members: Map(2) {
      "__constructor" => SymbolObject {
        flags: 16384,
        escapedName: "__constructor",
        declarations: [ [NodeObject] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: [Circular *6],
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      "hoge" => <ref *7> SymbolObject {
        flags: 4,
        escapedName: "hoge",
        declarations: [ [NodeObject] ],
        valueDeclaration: NodeObject {
          pos: 175,
          end: 198,
          kind: 169,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870913,
          transformFlags: 8193,
          parent: [NodeObject],
          original: undefined,
          emitNode: undefined,
          symbol: [Circular *7],
          localSymbol: undefined,
          modifiers: [Array],
          dotDotDotToken: undefined,
          name: [IdentifierObject],
          questionToken: undefined,
          type: [NodeObject],
          initializer: undefined,
          jsDoc: undefined
        },
        id: 0,
        mergeId: 0,
        parent: [Circular *6],
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      }
    },
    exports: Map(1) {
      "prototype" => SymbolObject {
        flags: 4194308,
        escapedName: "prototype",
        declarations: undefined,
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: [Circular *6],
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      }
    },
    exportSymbol: undefined,
    constEnumOnlyModule: undefined,
    isReferenced: undefined,
    lastAssignmentPos: undefined,
    links: undefined
  },
  localSymbol: undefined,
  modifiers: undefined,
  name: IdentifierObject {
    pos: 87,
    end: 156,
    kind: 80,
    id: 0,
    flags: 0,
    transformFlags: 0,
    parent: [Circular *3],
    emitNode: undefined,
    escapedText: "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
    jsDoc: undefined,
    flowNode: { flags: 2, id: 0, node: undefined, antecedent: undefined },
    symbol: undefined
  },
  typeParameters: undefined,
  heritageClauses: undefined,
  members: [
    <ref *5> NodeObject {
      pos: 158,
      end: 203,
      kind: 176,
      id: 0,
      flags: 512,
      modifierFlagsCache: 536870912,
      transformFlags: 9217,
      parent: [Circular *3],
      original: undefined,
      emitNode: undefined,
      symbol: SymbolObject {
        flags: 16384,
        escapedName: "__constructor",
        declarations: [ [Circular *5] ],
        valueDeclaration: undefined,
        id: 0,
        mergeId: 0,
        parent: <ref *6> SymbolObject {
          flags: 32,
          escapedName: "ref_da030cb1de29fad61c37c573b32ed30449df12e581bcac6a0e0bfc342f06a0d6",
          declarations: [Array],
          valueDeclaration: [Circular *3],
          id: 1,
          mergeId: 0,
          parent: undefined,
          members: [Map],
          exports: [Map],
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        },
        members: undefined,
        exports: undefined,
        exportSymbol: undefined,
        constEnumOnlyModule: undefined,
        isReferenced: undefined,
        lastAssignmentPos: undefined,
        links: undefined
      },
      localSymbol: undefined,
      modifiers: undefined,
      parameters: [
        NodeObject {
          pos: 175,
          end: 198,
          kind: 169,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870913,
          transformFlags: 8193,
          parent: [Circular *5],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: [Array],
          dotDotDotToken: undefined,
          name: [IdentifierObject],
          questionToken: undefined,
          type: [NodeObject],
          initializer: undefined,
          jsDoc: undefined
        },
        pos: 175,
        end: 198,
        hasTrailingComma: false,
        transformFlags: 8193
      ],
      body: NodeObject {
        pos: 199,
        end: 203,
        kind: 241,
        id: 0,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 0,
        parent: [Circular *5],
        original: undefined,
        emitNode: undefined,
        statements: [
          pos: 201,
          end: 201,
          hasTrailingComma: false,
          transformFlags: 0
        ],
        multiLine: false,
        jsDoc: undefined,
        locals: undefined,
        nextContainer: undefined
      },
      typeParameters: undefined,
      type: undefined,
      typeArguments: undefined,
      jsDoc: undefined,
      locals: Map(1) {
        "hoge" => SymbolObject {
          flags: 1,
          escapedName: "hoge",
          declarations: [Array],
          valueDeclaration: [NodeObject],
          id: 0,
          mergeId: 0,
          parent: undefined,
          members: undefined,
          exports: Map(0) {},
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        }
      },
      nextContainer: <ref *8> NodeObject {
        pos: 187,
        end: 198,
        kind: 184,
        id: 0,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 1,
        parent: NodeObject {
          pos: 175,
          end: 198,
          kind: 169,
          id: 0,
          flags: 0,
          modifierFlagsCache: 536870913,
          transformFlags: 8193,
          parent: [Circular *5],
          original: undefined,
          emitNode: undefined,
          symbol: [SymbolObject],
          localSymbol: undefined,
          modifiers: [Array],
          dotDotDotToken: undefined,
          name: [IdentifierObject],
          questionToken: undefined,
          type: [Circular *8],
          initializer: undefined,
          jsDoc: undefined
        },
        original: undefined,
        emitNode: undefined,
        symbol: SymbolObject {
          flags: 2048,
          escapedName: "__type",
          declarations: [Array],
          valueDeclaration: undefined,
          id: 0,
          mergeId: 0,
          parent: undefined,
          members: [Map],
          exports: undefined,
          exportSymbol: undefined,
          constEnumOnlyModule: undefined,
          isReferenced: undefined,
          lastAssignmentPos: undefined,
          links: undefined
        },
        localSymbol: undefined,
        typeParameters: undefined,
        parameters: [
          pos: 189,
          end: 189,
          hasTrailingComma: false,
          transformFlags: 0
        ],
        type: TokenObject {
          pos: 193,
          end: 198,
          kind: 116,
          id: 0,
          flags: 0,
          transformFlags: 1,
          parent: [Circular *8],
          emitNode: undefined
        },
        modifiers: undefined,
        jsDoc: undefined,
        locals: Map(0) {},
        nextContainer: undefined,
        typeArguments: undefined
      },
      endFlowNode: { flags: 2050, id: 0, node: undefined, antecedent: undefined },
      returnFlowNode: { flags: 2050, id: 0, node: undefined, antecedent: undefined }
    },
    pos: 158,
    end: 203,
    hasTrailingComma: false,
    transformFlags: 9217
  ],
  jsDoc: undefined
}

